configuration: Release

version: 0.0.1.{build}

notifications:
-   provider: Email
    to: abramov.dmitry92@gmail.com
    subject: '{{projectName}}. Build status: {{status}}'    
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true